In [3]:
import pandas as pd
dff=pd.read_csv("Zomato Restaurants Dataset export 2025-09-28 20-08-54.csv")
dff

,Unnamed: 0,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,Unnamed: 9,area,local address
0,0,#FeelTheROLL,Quick Bites,3.4,7,200,No,No,Fast Food,0,Bellandur,Bellandur
1,1,#L-81 Cafe,Quick Bites,3.9,48,400,Yes,No,"Fast Food, Beverages",1,"Byresandra,Tavarekere,Madiwala",HSR
2,2,#refuel,Cafe,3.7,37,400,Yes,No,"Cafe, Beverages",2,Bannerghatta Road,Bannerghatta Road
3,3,'@ Biryani Central,Casual Dining,2.7,135,550,Yes,No,"Biryani, Mughlai, Chinese",3,Marathahalli,Marathahalli
4,4,'@ The Bbq,Casual Dining,2.8,40,700,Yes,No,"BBQ, Continental, North Indian, Chinese, Bever...",4,Bellandur,Bellandur
...,...,...,...,...,...,...,...,...,...,...,...,...
7100,7100,Zoey's,Cafe,4.3,894,600,Yes,No,"Cafe, Italian, Continental, Burger",7100,Bellandur,Sarjapur Road
7101,7101,ZOROY Luxury Chocolate,Dessert Parlor,4.0,68,250,Yes,No,Desserts,7101,Brigade Road,Church Street
7102,7102,Zu's Doner Kebaps,"Takeaway, Delivery",3.7,33,350,No,No,"Turkish, Fast Food, Biryani, Chinese",7102,Malleshwaram,RT Nagar
7103,7103,Zyara,Casual Dining,3.8,191,650,Yes,No,"North Indian, Mughlai, Chinese",7103,Kammanahalli,HBR Layout
7104,7104,Zyksha,Food Truck,3.4,9,200,No,No,Fast Food,7104,Bannerghatta Road,South Bangalore

In [4]:
df=dff["num of ratings"]
print(df)

0         7
1        48
2        37
3       135
4        40
       ...
7100    894
7101     68
7102     33
7103    191
7104      9
Name: num of ratings, Length: 7105, dtype: int64

In [10]:
df=dff.tail()
df

,Unnamed: 0,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,Unnamed: 9,area,local address
7100,7100,Zoey's,Cafe,4.3,894,600,Yes,No,"Cafe, Italian, Continental, Burger",7100,Bellandur,Sarjapur Road
7101,7101,ZOROY Luxury Chocolate,Dessert Parlor,4.0,68,250,Yes,No,Desserts,7101,Brigade Road,Church Street
7102,7102,Zu's Doner Kebaps,"Takeaway, Delivery",3.7,33,350,No,No,"Turkish, Fast Food, Biryani, Chinese",7102,Malleshwaram,RT Nagar
7103,7103,Zyara,Casual Dining,3.8,191,650,Yes,No,"North Indian, Mughlai, Chinese",7103,Kammanahalli,HBR Layout
7104,7104,Zyksha,Food Truck,3.4,9,200,No,No,Fast Food,7104,Bannerghatta Road,South Bangalore

In [24]:
from scipy import stats
import numpy as np
data=[4.3,4.0,3.7,2,4.3,3.3,3.3,3.4,3.7,2.8]
ci= stats.t.interval(
    confidence =0.95,
    df=len(data) -1,
    loc=np.mean(data),
    scale=stats.sem(data)

)

In [25]:
print("95% Confidence Interval :")

print("Lower;",ci[0])
print("Upper:",ci[1])

95% Confidence Interval :
Lower; 2.9777762018266536
Upper: 3.9822237981733455

In [23]:
from math import sqrt
data=[4.3,4.0,3.7,3.8,3.4,2.8,3.4,3.8,4.3,2.8,
      4.4,41,4,4,1,3.5,3.9,3.4,3.7,3.5,4.1,4.2,
       4,4,3.6,2.9,3.9,3.7,3.3,3.1,3.6,2.8,4.3
      ]
std=3
ci=stats.norm.interval(
    0.95,
    loc=np.mean(data),
    scale=std/np.sqrt(len(data))
)
print("Number of data:",len(data))
print("mean:",np.mean(data))
print("95% Confidence Interval:")
print("Lower:",ci[0])
print("Upper:",ci[1])

Number of data: 33
mean: 4.733333333333334
95% Confidence Interval:
Lower: 3.7097755247743676
Upper: 5.756891141892301

In [19]:
student=50
mean=165
sd=10
ci=stats.norm.interval(
    0.95,
    loc=mean,
    scale=sd/np.sqrt(student)
)
print("95% Confidence Interval:")
print("Lower:",ci[0])
print("Upper:",ci[1])

95% Confidence Interval:
Lower: 162.22819235130063
Upper: 167.77180764869937

In [20]:
#Salaries
mean=25000,
sd=4000
n=30
ci=stats.norm.interval(
    0.95,
    loc=mean,
    scale=sd/np.sqrt(n)
)
print("95% Confidence Interval:")
print("Lower:",ci[0])
print("Upper:",ci[1])

95% Confidence Interval:
Lower: [23568.64468503]
Upper: [26431.35531497]

In [21]:
#exam
mean=70
sd=12
n=100
ci=stats.norm.interval(
    0.95,
    loc=mean,
    scale=sd/np.sqrt(n)
)
print("95% Confidence Interval:")
print("Lower:",ci[0])
print("Upper:",ci[1])

95% Confidence Interval:
Lower: 67.64804321855193
Upper: 72.35195678144807

In [22]:
#Bottle fill
mean=500
sd=8
n=40
ci=stats.norm.interval(
    0.99,
    loc=mean,
    scale=sd/np.sqrt(n)
)
print("95% Confidence Interval:")
print("Lower:",ci[0])
print("Upper:",ci[1])

95% Confidence Interval:
Lower: 496.7418050147921
Upper: 503.2581949852079